#!/usr/bin/env node
/**
 * release-version.mjs — single source of truth for release metadata.
 *
 * Reads the app version (tauri.conf.json) and, when present, the bundled
 * runtime manifest (versions.json, generated by bundle-runtime.mjs in CI).
 *
 * Modes:
 *   (no args)      human-readable one-liner
 *   --json         {"desktop":"0.1.0","dsh":"0.1.0-rc.6","node":"24.19.0"}
 *   --github       GITHUB_OUTPUT lines (for workflow step outputs)
 *   --check        verify the pushed tag (GITHUB_REF_NAME) equals the app
 *                  version — exit 1 on mismatch (versioning contract)
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const conf = JSON.parse(await readFile(path.join(ROOT, "src-tauri", "tauri.conf.json"), "utf8"));
const desktop = conf.version;
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(desktop)) {
  console.error(`[release-version] invalid app version in tauri.conf.json: ${desktop}`);
  process.exit(1);
}

let dsh = "?";
let node = "?";
try {
  const manifest = JSON.parse(
    await readFile(path.join(ROOT, "src-tauri", "resources", "runtime", "versions.json"), "utf8"),
  );
  dsh = manifest.dshVersion || dsh;
  node = manifest.nodeVersion || node;
} catch {
  // versions.json is generated by the bundle step before this script runs in
  // CI; locally it may be absent — report "?" rather than failing.
}

const mode = process.argv[2] || "";
const refName = process.env.GITHUB_REF_NAME || "";

if (mode === "--check") {
  if (!refName.startsWith("v")) {
    // not a tag build — nothing to check
    console.log("[release-version] not a tag build; skip");
    process.exit(0);
  }
  if (refName !== `v${desktop}`) {
    console.error(
      `[release-version] tag ${refName} != app version ${desktop} — bump src-tauri/tauri.conf.json to match the tag (see VERSIONING.md)`,
    );
    process.exit(1);
  }
  console.log(`[release-version] tag ${refName} matches app version`);
  process.exit(0);
}

if (mode === "--json") {
  console.log(JSON.stringify({ desktop, dsh, node }));
  process.exit(0);
}

if (mode === "--github") {
  console.log(`desktop=${desktop}`);
  console.log(`dsh=${dsh}`);
  console.log(`node=${node}`);
  process.exit(0);
}

console.log(`DSH Desktop v${desktop} · dsh ${dsh} · node v${node}`);
